// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ3b4x7C0XuF4XHEnXOmk8HmoYJY1ziak',
    appId: '1:903361753014:web:160c24afb23f0e7270db17',
    messagingSenderId: '903361753014',
    projectId: 'people-731e5',
    authDomain: 'people-731e5.firebaseapp.com',
    databaseURL: 'https://people-731e5-default-rtdb.firebaseio.com',
    storageBucket: 'people-731e5.firebasestorage.app',
    measurementId: 'G-GRJ4D0C5NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3G5Sp_kCVkGL79JO-_oPWkC2c_EswmSE',
    appId: '1:903361753014:android:77f0a26ef53640a470db17',
    messagingSenderId: '903361753014',
    projectId: 'people-731e5',
    databaseURL: 'https://people-731e5-default-rtdb.firebaseio.com',
    storageBucket: 'people-731e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgaXTWZtw68Ah49d5NqFSMwk-AUrOiIhA',
    appId: '1:903361753014:ios:c2e63e28451c5de270db17',
    messagingSenderId: '903361753014',
    projectId: 'people-731e5',
    databaseURL: 'https://people-731e5-default-rtdb.firebaseio.com',
    storageBucket: 'people-731e5.firebasestorage.app',
    iosBundleId: 'com.example.onlineVoting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgaXTWZtw68Ah49d5NqFSMwk-AUrOiIhA',
    appId: '1:903361753014:ios:c2e63e28451c5de270db17',
    messagingSenderId: '903361753014',
    projectId: 'people-731e5',
    databaseURL: 'https://people-731e5-default-rtdb.firebaseio.com',
    storageBucket: 'people-731e5.firebasestorage.app',
    iosBundleId: 'com.example.onlineVoting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ3b4x7C0XuF4XHEnXOmk8HmoYJY1ziak',
    appId: '1:903361753014:web:8d8a4f48901367b570db17',
    messagingSenderId: '903361753014',
    projectId: 'people-731e5',
    authDomain: 'people-731e5.firebaseapp.com',
    databaseURL: 'https://people-731e5-default-rtdb.firebaseio.com',
    storageBucket: 'people-731e5.firebasestorage.app',
    measurementId: 'G-XKX3WFYJNM',
  );
}
